# Change these first
owner: Mixtery # Your GitHub organization or username, where this repository lives
repo: mixtery.github.io # The name of this repository

sites:
  - name: Webserver
    url: https://terlouw.ai
  - name: Mailserver
    url: https://outlook.office.com
  - name: athena.terlouw.ai
    url: https://athena.terlouw.ai
  - name: artemis.terlouw.ai
    url: https://aphrodite.terlouw.ai
  - name: artemis.terlouw.ai
    url: https://artemis.terlouw.ai
  - name: API 3.6b
    url: https://namecheap.com
  - name: LinkCon 3
    url: https://versio.nl


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.terlouw.ai
  # baseUrl: /your-repo-name
  logoUrl: https://terlouw.ai/wp-content/uploads/2023/01/test-logos-11-300x300.png
  name: Terlouw Artificial Intellegence Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: For more information about our services, visit https://terlouw.ai
  navbar:
    - title: Status
      href: /
    - title: Terlouw Artificial Intelligence
      href: https://terlouw.ai

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
